#!/usr/bin/env python3
"""
128 Compiler — Proof of Concept.
Translates 128 language source to Fortran .so calls + FLUX bytecode.

Usage:
    python3 compile128.py program.128       # Compile to Fortran + FLUX
    python3 compile128.py program.128 --run  # Compile AND execute
    python3 compile128.py --example          # Show example program
"""

import ctypes, json, os, subprocess, sys, time, urllib.request

PLATO = "http://localhost:8847"

# ══════════════════════════════════════════════════════════════════════════
# LEXER / PARSER
# ══════════════════════════════════════════════════════════════════════════

class Node:
    def __init__(self, type, **kwargs):
        self.type = type
        self.__dict__.update(kwargs)
    def __repr__(self):
        return f"{self.type}({self.__dict__})"

def tokenize(source):
    tokens = []
    for line in source.strip().split("\n"):
        line = line.strip()
        if not line or line.startswith("//") or line.startswith("#"):
            continue
        # Split on whitespace, parens, brackets, semicolons, commas
        buf = ""
        for ch in line:
            if ch in "()[];,":
                if buf: tokens.append(buf); buf = ""
                tokens.append(ch)
            elif ch in " \t":
                if buf: tokens.append(buf); buf = ""
            else:
                buf += ch
        if buf: tokens.append(buf)
    return tokens

def parse(tokens):
    """Parse tokens into a list of nodes."""
    nodes = []
    i = 0
    while i < len(tokens):
        t = tokens[i]
        
        if t == "room":
            name = tokens[i+1]
            size = int(tokens[i+3].rstrip("]")) if "]" in tokens[i+1] else 1000
            if tokens[i+1].count("[") > 0:
                name = tokens[i+1].split("[")[0]
                size = int(tokens[i+1].split("[")[1].rstrip("]"))
            nodes.append(Node("declare", name=name, size=size,
                             decl_type="room", temporal=False))
            i += 2 if "]" in tokens[i+1] else 4
            
        elif t == "temporal":
            name = tokens[i+1].split("[")[0]
            size = int(tokens[i+1].split("[")[1].rstrip("]"))
            nodes.append(Node("declare", name=name, size=size,
                             decl_type="temporal", temporal=True))
            i += 2
            
        elif t == "penrose":
            name = tokens[i+1]
            iters = int(tokens[i+3])
            nodes.append(Node("penrose", name=name, iterations=iters))
            i += 4
            
        elif t in ("contract", "spline", "gradient", "recall", "window", "penrose"):
            op = t
            # Collect args until semicolon or end
            args = []
            i += 1  # skip past the keyword
            while i < len(tokens) and tokens[i] not in (";",):
                if tokens[i] not in ("(", ")", ","):
                    args.append(tokens[i].rstrip("),;"))
                i += 1
            nodes.append(Node("op", op=op, args=args))
            
        else:
            i += 1
    
    return nodes


# ══════════════════════════════════════════════════════════════════════════
# CODE GENERATORS
# ══════════════════════════════════════════════════════════════════════════

def gen_fortran(nodes):
    """Generate Fortran source from parsed nodes."""
    lines = [
        "! Generated by 128 compiler",
        "program plat128",
        "  use, intrinsic :: iso_c_binding",
        "  implicit none",
        "  integer(c_int32_t) :: i, nr, n",
        "  integer(c_int32_t), allocatable :: a(:), b(:), r(:)",
    ]
    
    for node in nodes:
        if node.type == "declare":
            pass  # handled at runtime
        elif node.type == "op":
            if node.op == "contract" and len(node.args) >= 3:
                lines.append(f"  call contract({node.args[0]}, size({node.args[0]}), "
                           f"{node.args[1]}, size({node.args[1]}), {node.args[2]}, nr)")
                lines.append(f"  print *, 'contract: ', nr, ' matches'")
            elif node.op == "spline" and len(node.args) >= 3:
                lines.append(f"  allocate(r(size({node.args[0]})))")
                lines.append(f"  call spline({node.args[0]}, {node.args[1]}, "
                           f"size({node.args[0]}), {node.args[2]}, r)")
            elif node.op == "gradient" and len(node.args) >= 1:
                lines.append(f"  call gradient({node.args[0]}, size({node.args[0]}), r)")
    
    lines.append("end program plat128")
    return "\n".join(lines)

def gen_flux_bytecode(nodes):
    """Generate FLUX bytecode (hex bytes) from parsed nodes."""
    bytes_out = []
    
    # FLUX ISA extension opcodes
    OPCODES = {
        "contract": 0xF0,
        "spline": 0xF1,
        "gradient": 0xF2,
    }
    
    for node in nodes:
        if node.type == "op" and node.op in OPCODES:
            opcode = OPCODES[node.op]
            a = int(node.args[0]) if node.args[0].isdigit() else 0
            b = int(node.args[1]) if len(node.args) > 1 and node.args[1].isdigit() else 0
            c = int(node.args[2]) if len(node.args) > 2 and node.args[2].isdigit() else 0
            bytes_out.extend([opcode, a & 0xFF, b & 0xFF, c & 0xFF])
    
    return bytes(bytes_out)


# ══════════════════════════════════════════════════════════════════════════
# BACKEND EXECUTOR
# ══════════════════════════════════════════════════════════════════════════

def execute_fortran(nodes):
    """Execute operations directly against the Fortran .so."""
    lib = ctypes.CDLL("/usr/local/lib/libplato_math.so")
    lib.contract.argtypes = [ctypes.POINTER(ctypes.c_int32), ctypes.c_int32,
        ctypes.POINTER(ctypes.c_int32), ctypes.c_int32, ctypes.c_int32,
        ctypes.POINTER(ctypes.c_int32)]
    lib.spline.argtypes = [ctypes.POINTER(ctypes.c_int32), ctypes.POINTER(ctypes.c_int32),
        ctypes.c_int32, ctypes.c_int32, ctypes.POINTER(ctypes.c_int32)]
    lib.gradient.argtypes = [ctypes.POINTER(ctypes.c_int32), ctypes.c_int32,
        ctypes.POINTER(ctypes.c_int32)]
    
    buffers = {}
    results = []
    
    for node in nodes:
        if node.type == "declare":
            size = node.size
            arr = (ctypes.c_int32 * size)()
            for i in range(size):
                arr[i] = i * 1000
            buffers[node.name] = arr
            results.append(f"  Declared {node.name}[{size}] ({node.decl_type})")
            
        elif node.type == "op":
            if node.op == "contract" and len(node.args) >= 3:
                a_name = node.args[0]
                b_name = node.args[1]
                threshold = int(node.args[2])
                a = buffers.get(a_name)
                b = buffers.get(b_name)
                if a is not None and b is not None:
                    t0 = time.time()
                    nr = ctypes.c_int32(0)
                    lib.contract(a, len(a), b, len(b), threshold, ctypes.byref(nr))
                    dt = time.time() - t0
                    results.append(f"  contract({a_name}, {b_name}, {threshold}): "
                                   f"{nr.value} matches in {dt*1000:.2f}ms "
                                   f"({len(a)*len(b)/dt/1e6:.0f}M pairs/s)")
            
            elif node.op == "spline" and len(node.args) >= 3:
                a_name = node.args[0]
                b_name = node.args[1]
                mu = int(node.args[2])
                a = buffers.get(a_name)
                b = buffers.get(b_name)
                if a is not None and b is not None:
                    n = min(len(a), len(b))
                    r = (ctypes.c_int32 * n)()
                    t0 = time.time()
                    lib.spline(a, b, n, mu, r)
                    dt = time.time() - t0
                    results.append(f"  spline({a_name}, {b_name}, mu={mu}): "
                                   f"{n} tiles in {dt*1000:.3f}ms "
                                   f"({n/dt/1e6:.0f}M tiles/s)")
    
    return "\n".join(results)


# ══════════════════════════════════════════════════════════════════════════
# MAIN
# ══════════════════════════════════════════════════════════════════════════

def compile_and_run(source, do_run=False):
    tokens = tokenize(source)
    nodes = parse(tokens)
    
    print("=" * 60)
    print("128 Compiler — Proof of Concept")
    print("=" * 60)
    
    print(f"\nSource ({len(source)} chars):")
    for line in source.strip().split("\n"):
        print(f"  {line.strip()}")
    
    print(f"\nParsed ({len(nodes)} nodes):")
    for n in nodes:
        print(f"  {n}")
    
    print(f"\nGenerated Fortan ({len(gen_fortran(nodes))} chars):")
    for line in gen_fortran(nodes).split("\n")[:5]:
        print(f"  {line}")
    print(f"  ...")
    
    print(f"\nGenerated FLUX bytecode ({len(gen_flux_bytecode(nodes))} bytes):")
    bc = gen_flux_bytecode(nodes)
    if bc:
        hex_str = " ".join(f"{b:02X}" for b in bc)
        print(f"  {hex_str}")
    
    if do_run:
        print(f"\nExecuting (Fortran backend):")
        result = execute_fortran(nodes)
        print(result)
        print(f"\n  ✅ 128 program executed successfully")
    
    return nodes

EXAMPLE_PROGRAM = """
// 128 language example — PLATO tile operations
room tiles[1000];
room reference[1000];

// Contract: find matching tile pairs
result = contract(tiles, reference, 500);

// Spline: interpolate between states
result = spline(tiles, reference, 512);

// Gradient: compute change across tiles
result = gradient(tiles);
"""

if __name__ == "__main__":
    if "--example" in sys.argv:
        print(EXAMPLE_PROGRAM)
        sys.exit(0)
    
    source = EXAMPLE_PROGRAM
    if len(sys.argv) > 1 and sys.argv[1].endswith(".128"):
        with open(sys.argv[1]) as f:
            source = f.read()
    
    do_run = "--run" in sys.argv
    compile_and_run(source, do_run)
